language: d

d:
  - dmd-2.067.0
  - dmd-2.065.0
  - dmd-2.066.1
  - gdc-4.8.2
  - gdc-4.9.0
  - ldc-0.14.0
  - ldc-0.15.1
  
os:
  - linux

install:
  # Install doveralls from the latest github release
  - wget -q -O - "http://bit.ly/Doveralls" | bash
  # Or, if you know what version you want, like v1.1.2, you can simply use this instead:
  #- wget -O doveralls https://github.com/ColdenCullen/doveralls/releases/download/v1.1.2/doveralls_travis

script:
  - dub test -b unittest-cov
  - ./doveralls
